name       : qt6-wayland
version    : 6.3.0
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtwayland-everywhere-src-6.3.0.tar.xz : e7b567f6e43ffc5918d4aa825ce1eced66a00cb0a87133b2912ba5c1b2a02190
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Wayland Library
description: |
    The Qt Wayland Compositor is a module that provides convenient and powerful QML and C++ APIs for developing custom display servers based on the Wayland protocol. The display server, often called a compositor, displays content from client applications that support the Wayland protocol.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcomposite)
rundeps    :
    - devel :
        - libxcomposite-devel
        - qt6-declarative-devel
        - wayland-devel
        - wayland-protocols-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
