name       : qt6-wayland
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtwayland-everywhere-src-6.2.2.tar.xz : 2d3652b3ecb5d8c9493c938b3d379dd700800859bb19033e8024e29d8deb3618
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Wayland Library
description: |
    The Qt Wayland Compositor is a module that provides convenient and powerful QML and C++ APIs for developing custom display servers based on the Wayland protocol. The display server, often called a compositor, displays content from client applications that support the Wayland protocol.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcomposite)
rundeps    :
    - devel :
        - libxcomposite-devel
        - qt6-declarative-devel
        - wayland-devel
        - wayland-protocols-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
